default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pocketify_development

test:
  <<: *default
  database: pocketify_test

production:
  <<: *default
  database: pocketify_production
  username: guilherme
  password: <%= ENV['GUILHERME_DATABASE_PASSWORD'] %>
